spring:
  application:
    name: log-transform-service

  datasource:
    url: jdbc:h2:mem:logsdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
