replicaCount: 1

image:
  repository: ghcr.io/priyankalattala/log-ingestion-analysis-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "local"

ingress:
  enabled: true
  className: "nginx"         
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: log-ingestion.local
      paths:
        - path: /
          pathType: Prefix
  tls: []                     
